const items = [{
    id:'001',
    Image :'Site Files/NeckLace7.jpg',
    name :'Bridal Wedding Gold Necklace Set',
    currentPrice : 513000,
    originalPrice : 540000,
    discount:5,
    class:'bridal-set',
},
{
    id:'002',
    Image :'Site Files/Ring6.jpg',
    name :'Gold Ring',
    currentPrice : 29400,
    originalPrice : 30000,
    discount:2,
    class:'Ring',
},
{
    id:'003',
    Image :'Site Files/NeckLace12.webp',
    name :'Gold-Plated Stone-studded Necklace',
    currentPrice : 950400,
    originalPrice :990000,
    discount:4,
    class:'gold-plated-set',
},
{
    id:'004',
    Image :'Site Files/Earing10.jpg',
    name :'Diamond Earring',
    currentPrice : 99500,
    originalPrice : 100000,
    discount:5,
    class:'D-Earring',
},{
    id:'005',
    Image :'Site Files/Bengals6.jpg',
    name :'Gold Bengals',
    currentPrice : 4656000,
    originalPrice : 480000,
    discount:3,
    class:'Gold Bengals',
},
{
    id:'006',
    Image :'Site Files/NeckLace9.jpg',
    name :'All Pearls Stone-studded Set',
    currentPrice : 680800,
    originalPrice : 740000,
    discount:8,
    class:'pearls-set',
},
{
    id:'007',
    Image :'Site Files/Earing7.jpg',
    name :'Stone-studded Earrings',
    currentPrice : 150739,
    originalPrice :153816,
    discount:3,
    class:'S-Earrings',
},
{
    id:'008',
    Image :'Site Files/NeckLace4.jpg',
    name :'Pearls Choker NeckLace',
    currentPrice : 395200,
    originalPrice : 416000,
    discount:5,
    class:'Pearls Choker',
},]
